# Schema for the configuration files of the SmartGlossary module.

smart_glossary.smart_glossary.*:
   type: config_entity
   label: 'Smart Glossary'
   mapping:
     title:
       type: label
       label: 'Title'
     id:
       type: string
       label: 'ID'
     connection_id:
        type: string
        label: 'Connection ID'
     base_path:
       type: string
       label: 'Type'
     language_mapping:
       type: undefined
       label: 'Language mapping'
     visual_mapper_settings:
       type: undefined
       label: 'VisualMapper settings'
     advanced_settings:
       type: undefined
       label: 'Advanced settings'